# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formular.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Container = QtWidgets.QVBoxLayout()
        self.Container.setContentsMargins(-1, -1, 0, -1)
        self.Container.setObjectName("Container")
        self.verticalLayout_2.addLayout(self.Container)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ladenpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ladenpushButton.setObjectName("ladenpushButton")
        self.verticalLayout.addWidget(self.ladenpushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 6, 1, 1)
        self.labelOrder2 = QtWidgets.QLabel(self.centralwidget)
        self.labelOrder2.setObjectName("labelOrder2")
        self.gridLayout.addWidget(self.labelOrder2, 1, 1, 1, 1)
        self.width2Slider = QtWidgets.QSlider(self.centralwidget)
        self.width2Slider.setMinimum(1)
        self.width2Slider.setSingleStep(2)
        self.width2Slider.setPageStep(11)
        self.width2Slider.setOrientation(QtCore.Qt.Horizontal)
        self.width2Slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.width2Slider.setTickInterval(2)
        self.width2Slider.setObjectName("width2Slider")
        self.gridLayout.addWidget(self.width2Slider, 0, 2, 1, 1)
        self.labelWidth2 = QtWidgets.QLabel(self.centralwidget)
        self.labelWidth2.setObjectName("labelWidth2")
        self.gridLayout.addWidget(self.labelWidth2, 0, 1, 1, 1)
        self.order2Slider = QtWidgets.QSlider(self.centralwidget)
        self.order2Slider.setMinimum(1)
        self.order2Slider.setMaximum(10)
        self.order2Slider.setSingleStep(1)
        self.order2Slider.setPageStep(1)
        self.order2Slider.setOrientation(QtCore.Qt.Horizontal)
        self.order2Slider.setObjectName("order2Slider")
        self.gridLayout.addWidget(self.order2Slider, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.width3Slider = QtWidgets.QSlider(self.centralwidget)
        self.width3Slider.setMinimum(1)
        self.width3Slider.setSingleStep(2)
        self.width3Slider.setPageStep(11)
        self.width3Slider.setOrientation(QtCore.Qt.Horizontal)
        self.width3Slider.setTickInterval(2)
        self.width3Slider.setObjectName("width3Slider")
        self.gridLayout.addWidget(self.width3Slider, 0, 5, 1, 1)
        self.order3Slider = QtWidgets.QSlider(self.centralwidget)
        self.order3Slider.setMinimum(1)
        self.order3Slider.setMaximum(10)
        self.order3Slider.setSingleStep(1)
        self.order3Slider.setPageStep(1)
        self.order3Slider.setOrientation(QtCore.Qt.Horizontal)
        self.order3Slider.setObjectName("order3Slider")
        self.gridLayout.addWidget(self.order3Slider, 1, 5, 1, 1)
        self.labelWidth3 = QtWidgets.QLabel(self.centralwidget)
        self.labelWidth3.setObjectName("labelWidth3")
        self.gridLayout.addWidget(self.labelWidth3, 0, 4, 1, 1)
        self.labelOrder3 = QtWidgets.QLabel(self.centralwidget)
        self.labelOrder3.setObjectName("labelOrder3")
        self.gridLayout.addWidget(self.labelOrder3, 1, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Rang"))
        self.label.setText(_translate("MainWindow", "Filterbreite"))
        self.ladenpushButton.setText(_translate("MainWindow", "Laden"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.labelOrder2.setText(_translate("MainWindow", "0"))
        self.labelWidth2.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Filterbreite"))
        self.label_2.setText(_translate("MainWindow", "Rang"))
        self.labelWidth3.setText(_translate("MainWindow", "0"))
        self.labelOrder3.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

